const STRAIGHTPOOL_MIN_PLAYERS = 2
const STRAIGHTPOOL_MAX_PLAYERS = 6
const STRAIGHTPOOL_DEFAULT_TARGET = 50
const STRAIGHTPOOL_MIN_TARGET = 10
const STRAIGHTPOOL_MAX_TARGET = 300
const STRAIGHTPOOL_MAX_HISTORY = 5
